---
title: "cranLogs"
author: "myTinyShinys"
output: 
  flexdashboard::flex_dashboard:
    css: styles.css
    theme: united
    orientation: rows
    social: [ menu ]
    # source_code: embed
runtime: shiny
---

```{r setup, include=FALSE}
library(flexdashboard)
library(plotly)
library(readr)
library(DT)
library(shiny)

library(feather)
library(dplyr)

# Import data
#df <- read_feather("data/allCranLogsBU.feather") # one-off
 df <- read_feather("data/allCranLogs.feather")
pkgs <- read_csv("data/packages.csv")
updates <- read_csv("data/updates.csv")
allByDay <- read_csv("data/allByDay.csv")
print(glimpse(allByDay))
#newpkgs <- read_csv("data/newPackages.csv")

# for use in selectInputs
packageChoice <- pkgs$name



```


New/Updated Packages
===================================== 

Inputs {.sidebar data-width=250}
-------------------------------------

``` {r}
includeMarkdown("new.md")
hr()
sliderInput("new","Select time scale in days",min=1,max=365,value=7)
#actionButton("go_new","Get Table")
hr()
includeMarkdown("updated.md")
```

Row
-----------------------------------------------------------------------



### New Packages - click on Package for CRAN entry information 

```{r}
##NB joins take a while - look at doing in daily update as data does not get any newer(but then not over varying spans which want)
output$newTable <- DT::renderDataTable({

  newOnes <-  df %>%
  group_by(package) %>%
  summarize(launched = min(date, na.rm = T)) %>%
  arrange(desc(launched)) %>%
  filter(launched > Sys.Date() - input$new)  #input$new
 
  
  newOnes %>%
  left_join(df) %>%
  group_by(package) %>%
   summarize(avDowns = round(sum(count) / n(), 0),
  minRank = min(rank, na.rm = TRUE)) %>%
  inner_join(newOnes) %>%
  left_join(pkgs, by = c("package" = "name")) %>%
  arrange(desc(avDowns)) %>%
  mutate(webUrl = paste0(
  'https://cran.r-project.org/web/packages/',
  package,
  '/index.html'
  )) %>%
  mutate(link = paste0("<a href=\"", webUrl, "\" target=\"_blank\">", package, "</a>")) %>%
  select(
  Package = link,
  Av_per_Day = avDowns,
  Top_rank = minRank,
  Released = launched,
  Description = description
  ) %>%
    arrange(desc(Released)) %>% 
  DT::datatable(
  class = 'compact stripe hover row-border order-column',
  rownames = TRUE,
  escape = FALSE,
  options = list(
  paging = TRUE,
  searching = TRUE,
  info = FALSE
  )
  )
  
})

dataTableOutput("newTable")

```

Row
-----------------------------------------------------------------------


### Updated 


```{r}

output$updatedTable <- DT::renderDataTable({
  updates %>%
  mutate(webUrl = paste0(
  'https://cran.r-project.org/web/packages/',
  package,
  '/index.html'
  )) %>%
  mutate(link = paste0("<a href=\"", webUrl, "\" target=\"_blank\">", package, "</a>")) %>%
  select(
  Package = link,
  Latest = count,
  Rank = rank,
  Updated,
  Description 
  )   %>%
    arrange(desc(Updated)) %>%
  DT::datatable(
  class = 'compact stripe hover row-border order-column',
  rownames = TRUE,
  escape = FALSE,
  options = list(
  paging = TRUE,
  searching = TRUE,
  info = FALSE
  )
  )
  
  
  
  })
  
  dataTableOutput("updatedTable")
  
```



Individual Packages
===================================== 

Inputs {.sidebar data-width=250}
-------------------------------------

``` {r}
# some background
includeMarkdown("info.md")
hr()

# select a default from top 50 current packages
default <-df %>% 
  filter(date==max(date)) %>% 
  arrange(desc(count)) %>% 
  head(50) %>% 
  .$package %>% 
  sample(1)

# interactive
selectInput(
"packages_Ind",
"Select (default random top 50 package)",
choices = packageChoice,
selected = default,
multiple = FALSE,
selectize = FALSE,
size = 20
)
hr()

```





``` {r data carpentry individual}

# saves repeating calculations
indData <- reactive({
data <-   df %>%
filter(package == input$packages_Ind & count > 0) %>%
arrange(rank)

downloads <- data %>%
summarize(tot = sum(count))

info = list(data = data, downloads = downloads)
return(info)
  
})

```

Row
-----------------------------------------------------------------------

### Package 

```{r}

renderValueBox({
  val <-
  paste0(input$packages_Ind, " - ", pkgs[pkgs$name == input$packages_Ind, ]$description)
  
  valueBox(value = val,
  icon = "fa-book")
  
  })



```


Row
-----------------------------------------------------------------------

### Daily Downloads 

```{r}


renderPlotly({
  
  
  df<- indData()$data 
  
 df %>%
  plot_ly(
  x = ~date,
  y = ~count,

 type="scatter",
  marker = list(color = "#007bff", size = 3),
  hoverinfo = "text",
  text = paste0(df$date, "<br> Count: ", df$count, "<br> Rank: ", df$rank)
  )  %>%
  
  layout(
  hovermode = "closest",
  xaxis = list(title = ""),
  yaxis = list(title = " ")
  )
  })


```


### Rank

```{r}

renderPlotly({
  df <- indData()$data
  
 df  %>%
  plot_ly(
  x = ~date,
  y = ~rank,
  #mode = "markers",
  type="scatter",
  marker = list(color = "#ff9000", size = 3),
  hoverinfo = "text",
  text = paste0(df$date, "<br> Rank: ", df$rank, "<br> Count: ", df$count)
  )  %>%
  layout(xaxis = list(title = ""),
  yaxis = list(autorange = "reversed", title = ""))
  })
  


```



Row
-----------------------------------------------------------------------

### Total Downloads

```{r}

renderValueBox({
  valueBox(value = format(indData()$downloads$tot, big.mark = ","),
  icon = "fa-download")
  
  })



```

### Highest Rank

```{r}

renderValueBox({
  valueBox(value = format(indData()$data$rank[1], big.mark = ","),
  icon = "fa-thumbs-up")
  
  })



```

Multiple Packages
===================================== 

Inputs {.sidebar data-width=250}
-------------------------------------

``` {r}
includeMarkdown("info.md")
hr()
selectInput("packages_Mult","Select or Start Typing ",choices=packageChoice,selected=c("rbokeh","ggvis","plotly","iplots","rggobi","googlevis"), multiple=TRUE)
actionButton("go_multiple","Get Tables")
```

Column {data-width=325}
-----------------------------------------------------------------------

### Daily Downloads - Zoom as required and Hover for details. Toggle package in legend to hide/show

```{r}

data_multiple <- eventReactive(input$go_multiple,{
  
  df %>%
  filter(package %in% input$packages_Mult)
  
})

```

```{r}


renderPlotly({
  
  data_multiple() %>% 
  plot_ly(
  x = ~date,
  y = ~count,
  #mode = "markers",
  type="scatter",
  color = ~package
  )  %>%
  layout(xaxis = list(title = ""),
  yaxis = list(title = ""))
  })


```

Column {data-width=325}
-----------------------------------------------------------------------

### Cumulative Downloads

```{r}


renderPlotly({
  
   data_multiple() %>%
    arrange(date) %>% 
    group_by(package) %>% 
    mutate(cum=cumsum(count)) %>% 
    plot_ly(x=~date,y=~cum,mode="lines", color=~package)
  })


```





Summarized Data
===================================== 

Column {data-width=650}
-----------------------------------------------------------------------

### Overall Downloads 




``` {r overall} 
DT::renderDataTable({
# df %>%
#     group_by(package) %>%
#     summarize(tot=sum(count),mean=round(mean(count),0),max=max(count),top_rank=min(rank))%>%
#     filter(package!="NA") %>% 
#     arrange(desc(tot)) %>%
#    DT::datatable(class='compact stripe hover row-border order-column',rownames=TRUE,options= list(paging = TRUE, searching = TRUE,info=FALSE))
  
df %>%
    group_by(package) %>%
     filter(date>"2012-10-30") %>% 
     mutate(top=ifelse(rank==1,1,0)) %>% 
    summarize(tot=sum(count),mean=round(mean(count),0),max=max(count),top_rank=min(rank),days_top=sum(top)) %>%
    filter(package!="NA") %>%
    arrange(desc(tot)) %>%
   DT::datatable(class='compact stripe hover row-border order-column',rownames=TRUE,options= list(paging = TRUE, searching = TRUE,info=FALSE))
})

```

Column {data-width=650}
-----------------------------------------------------------------------

### Cumulative and Daily Package downloads from RStudio 


``` {r downloads by day}  

renderPlotly({
 df %>% 
  group_by(date) %>% 
  summarize(daily=sum(count)) %>% 
  arrange(date) %>% 
  mutate(tot=cumsum(daily))  %>% 
  filter(date>="2012-11-01") %>% 
  plot_ly(x=~date,y=~tot/100, name="Cumulative (100m)") %>% 
  add_lines(line = list(color = "red")) %>% 
  layout(title="",
         xaxis=list(title=""),
         yaxis=list(title="",rangemode="tozero")) %>% 
  add_bars(x=~date,y=~daily,opacity=0.5, name="Daily Download")
 
})

```

### Cumulative and New CRAN Packages downloaded from RStudio


``` {r new packages by day}  

allByDay %>% 
  plot_ly(x=~date,y=~tot/1000, name="Cumulative ('000)") %>% 
  add_lines(line = list(color = "red")) %>% 
  layout(title="",
         xaxis=list(title=""),
         yaxis=list(title="Total Packages",rangemode="tozero")) %>% 
  add_bars(x=~date,y=~n,opacity=0.5, name="New daily")

```
